modLoader="javafml"
loaderVersion="[47,)" 
license="MIT"
clientSideOnly=true

[[mods]]
modId="demodisablermod"
version="${file.jarVersion}"
displayName="Demo Disabler"
displayTest="NONE" 
description='''Disables demo mode for multiplayer and chat!'''

[mods.features]
java_version="[17,)" 

[[dependencies.demodisablermod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.demodisablermod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1, 1.21)"
ordering="NONE"
side="BOTH"
