modLoader="javafml"
loaderVersion="[51,)" 
license="MIT"
clientSideOnly=true

[[mods]]
modId="demodisablermod"
version="${file.jarVersion}"
displayName="Demo Disabler"
displayTest="NONE" 
description='''Disables demo mode for multiplayer and chat!'''

[mods.features]
java_version="[21,)" 

[[dependencies.demodisablermod]]
modId="forge"
mandatory=true
versionRange="[51,)"
ordering="NONE"
side="BOTH"

[[dependencies.demodisablermod]]
modId="minecraft"
mandatory=true
versionRange="[1.21, 1.22)"
ordering="NONE"
side="BOTH"
